---
- hosts: localhost
  connection: local
  tasks:
    - name: set roles
      set_fact:
        roles: 
          - sync
      tags:
        - always

    - name: Display roles
      debug: "var=roles"
      tags:
        - always

    - name: Run roles
      include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ roles }}"
      tags:
        - always
