---
- name: Install pyhton and pip
  package: 
    name: "{{ item }}"
    state: latest
  become: yes
  loop:
    - python
    - python-pip

- name: Install neovim
  pip:
    name: neovim
    state: latest
