---
- name: Ubuntu python name
  set_fact: pyName="python3"
  when: ansible_distribution == 'Ubuntu'

- name: Archlinux python name
  set_fact: pyName="python"
  when: ansible_distribution == 'Archlinux'

- name: Install pyhton and pip
  package: 
    name: "{{ item }}"
    state: latest
  become: yes
  loop:
    - "{{ pyName }}"
    - python-pip
    - python-setuptools
    - python-neovim
