---
- name: Install tmux
  package:
    name: tmux
    state: latest
  become: yes

- name: Copy conf. files
  copy:
    mode: '744'
    src: "{{ item }}"
    dest: ~/
  with_fileglob:
    - ../files/*

- name: tmux.sh for ubuntu
  copy:
    mode: '744'
    src: ../files/tmux-ubuntu.sh
    dest: ~/tmux.sh
  when: ansible_distribution == 'Ubuntu'
