---
- name: Check if node is installed
  shell: which node
  register: result

- name: Download node
  get_url:
    url: "https://nodejs.org/dist/v16.15.1/node-v16.15.1-linux-x64.tar.xz"
    dest: "~/node.tar.xz"
  when: result.stdout.find('not found') == "-1"

- name: Create node dir
  file:
    mode: '644'
    path: "~/node"
    state: directory
  when: result.stdout.find('not found') == "-1"

- name: Unpack node.tar.xz
  unarchive:
    dest: "~/"
    mode: '644'
    src: "~/node.tar.xz"
  when: result.stdout.find('not found') == "-1"

- name: Copy node in the right dir
  copy:
    mode: '644'
    src: "{{ item }}"
    dest: ~/node
  with_fileglob:
    - ~/node-v16.15.1-linux-x64/*
  when: result.stdout.find('not found') == "-1"
  
- name: Remove ~/node-v16.15.1-linux-x64
  file:
    state: absent
    path: "~/node-v16.15.1-linux-x64/"
  when: result.stdout.find('not found') == "-1"

- name: Remove ~/node.tar.xz
  file:
    state: absent
    path: "~/node.tar.xz"
  when: result.stdout.find('not found') == "-1"
