---
- name: Dependencies
  ansible.builtin.package:
    name:
      - ninja-build 
      - gettext 
      - libtool 
      - libtool-bin 
      - autoconf 
      - automake 
      - cmake 
      - g++ 
      - pkg-config 
      - unzip 
      - curl 
      - doxygen
    state: latest
  become: yes
