---
- name: Create font dir
  file:
    state: directory
    path: "/usr/local/share/fonts/ttf/"
  become: yes

- name: Copy fonts
  copy:
    src: "{{ item }}"
    dest: "/usr/local/share/fonts/ttf"
  with_fileglob:
    - ../files/*
  become: yes

- name: Cache fonts
  shell: fc-cache -f -v
